# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

In [2]:
!pip install mdutils

  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Created wheel for mdutils: filename=mdutils-1.6.0-py3-none-any.whl size=20744 sha256=98c2f4f7a500f730137e432c34b0cf7cab40270e770326389db7c7d055b4656e
  Stored in directory: c:\users\edeng\appdata\local\pip\cache\wheels\2c\18\dc\d1968536d8f0c46c7180448ccc75f641fa2c3dea7bb02ea868
Successfully built mdutils


#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [5]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: D:/Programs/miniconda3/Library/include
    lib directory: D:/Programs/miniconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cp

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
x = np.zeros(10)
print(x.size)
print(x.itemsize)
print("array size in bytes:")
print(x.size * x.itemsize)

10
8
array size in bytes:
80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
x = np.zeros(10) 
x[4] = 1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
x = np.arange(5)
print(x)
print(x[::-1])

[0 1 2 3 4]
[4 3 2 1 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
x = [1, 2, 0, 0, 4, 0]
np.nonzero(x)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
np.random.random((3,3,3))

array([[[0.13641752, 0.48223367, 0.89135498],
        [0.82990052, 0.84545555, 0.14474749],
        [0.70165816, 0.5558394 , 0.6782077 ]],

       [[0.90816462, 0.98536949, 0.31159837],
        [0.95965959, 0.82201318, 0.00496142],
        [0.0119969 , 0.31532115, 0.751341  ]],

       [[0.98855001, 0.90319933, 0.9036987 ],
        [0.71615193, 0.7969533 , 0.36336042],
        [0.63866762, 0.36909748, 0.534351  ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
x = np.random.random((10,10))
print(x)
print(x.min(), x.max())

[[0.86510043 0.65599119 0.83143812 0.82859412 0.98891364 0.44981169
  0.12748466 0.55783637 0.06327973 0.98576844]
 [0.76874907 0.52408298 0.8907202  0.44930566 0.93272522 0.18961273
  0.47413873 0.56936808 0.3058495  0.77283395]
 [0.22506106 0.33201901 0.39660735 0.36626819 0.51934833 0.14549078
  0.67663526 0.34738754 0.72459968 0.24808688]
 [0.63388258 0.53334519 0.50060749 0.7120417  0.58747274 0.3422289
  0.4426632  0.23959582 0.56906187 0.07630685]
 [0.02072145 0.26903389 0.26367735 0.42898311 0.71621827 0.99544376
  0.31650611 0.77830045 0.43461906 0.34430812]
 [0.55694366 0.34920375 0.90226477 0.68818405 0.45052806 0.80040795
  0.30430882 0.29505147 0.21125844 0.99559516]
 [0.15767808 0.47406656 0.91268448 0.69227526 0.87371121 0.0839933
  0.1112384  0.84587421 0.3972571  0.61423682]
 [0.97669682 0.65379755 0.61702476 0.34683792 0.73168421 0.20328049
  0.07499239 0.78612362 0.95963476 0.58700471]
 [0.59526976 0.12201614 0.85677119 0.93046961 0.55303741 0.25527936
  0.54992756 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
x = np.random.random(30)
print(x)
print(x.mean())

[0.79236546 0.73313754 0.78044096 0.32112406 0.46425268 0.4972084
 0.71349257 0.35804289 0.63105529 0.67794724 0.14868087 0.47735784
 0.77963681 0.13370526 0.77576042 0.07872142 0.3830398  0.05267385
 0.96416961 0.99175596 0.96898435 0.14872963 0.92171915 0.84435404
 0.69439443 0.97526096 0.65587867 0.45262657 0.30513493 0.16413875]
0.562859680568777


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [31]:
3 * 0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [36]:
x = np.zeros((5,5))
x[np.arange(1,5), np.arange(4)] = np.arange(1,5)
print(x)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [46]:
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [47]:
x = np.random.random((6,7,8))
print(np.unravel_index(100, x.shape))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [48]:
square = np.array([[0,1], [1,0]])
x = np.tile(square, (4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [49]:
x = np.random.random((5,5))
x = (x - np.mean(x)) / np.std(x)
print(x)

[[ 1.15168698 -1.26045336  0.84297841  0.40018711 -0.4584782 ]
 [-0.09865151  1.10378886 -0.75921759 -0.40732708  0.15920552]
 [ 1.43864929 -0.23156732  1.30612632  0.9881289  -0.98987403]
 [-1.63786736 -1.66313407  0.74018632 -1.0801561  -1.60764931]
 [ 1.17787015  1.37224616  0.00592934 -0.04255531 -0.45005209]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [50]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

C:\Users\edeng\AppData\Local\Temp\ipykernel_27380\3034247072.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [51]:
x = np.random.random((5,3))
y = np.random.random((3,2))
print(np.dot(x, y))

[[0.18974587 0.53671564]
 [0.89741249 1.25803843]
 [0.66176284 0.95038427]
 [0.38219221 0.87536352]
 [0.20699187 0.50864801]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [53]:
x = np.arange(11)
x[(3 <= x) & (x <= 8)] *= -1
print(x)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [54]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [58]:
z = np.arange(5)
print(z**z)
print(2 << z >> 2)
print(z <- z)
print(1j*z)
print(z/1/1)
# print(z<z>z)

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [62]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\edeng\AppData\Local\Temp\ipykernel_27380\1422587819.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\edeng\AppData\Local\Temp\ipykernel_27380\1422587819.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\edeng\AppData\Local\Temp\ipykernel_27380\1422587819.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
x = np.random.random(10)
np.sign(x) * np.ceil(np.abs(x))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 30. How to find common values between two arrays? (★☆☆)

In [72]:
x = np.random.randint(0, 10, 10)
y = np.random.randint(0, 10, 10)
print(x)
print(y)
print(np.intersect1d(x, y))

[8 2 4 9 9 0 7 2 9 0]
[3 3 7 9 1 8 7 8 7 5]
[7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [73]:
#np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [75]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)

nan
1j


C:\Users\edeng\AppData\Local\Temp\ipykernel_27380\1919505774.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\edeng\AppData\Local\Temp\ipykernel_27380\1919505774.py:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [78]:
print(np.datetime64('today', 'D') - np.timedelta64(1, 'D'))
print(np.datetime64('today', 'D'))
print(np.datetime64('today', 'D') + np.timedelta64(1, 'D'))

2024-06-29
2024-06-30
2024-07-01


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [80]:
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [82]:
A = np.random.random((3,3))
B = np.random.random((3,3))
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)
print(A)

[[-0.26498965 -0.40497247 -0.39700153]
 [-0.07440759 -0.01567368 -0.40851015]
 [-0.16035891 -0.46003065 -0.81476515]]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [83]:
x = np.random.uniform(0, 10, 10)
print(x)
print(x - x % 1)
print(np.floor(x))
print(np.ceil(x) - 1)
print(x.astype(int))

[6.94605245 6.42193812 2.96231481 7.17310352 0.7956194  8.52698414
 8.17185059 5.3533388  2.74463726 9.70552482]
[6. 6. 2. 7. 0. 8. 8. 5. 2. 9.]
[6. 6. 2. 7. 0. 8. 8. 5. 2. 9.]
[6. 6. 2. 7. 0. 8. 8. 5. 2. 9.]
[6 6 2 7 0 8 8 5 2 9]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [84]:
x = np.tile(np.arange(5), (5, 1))
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [86]:
def gen():
    for i in range(10):
        yield np.random.randint(5)

x = np.fromiter(gen(), dtype=int)
print(x)

[3 0 1 1 0 3 1 2 0 4]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [91]:
np.linspace(0, 1, 12)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [93]:
x = np.random.random(10)
x.sort()
print(x)

[2.95213566e-05 1.78987086e-01 2.92084723e-01 3.60598789e-01
 5.06417390e-01 7.31352386e-01 8.65839244e-01 8.68677025e-01
 8.92861625e-01 9.44989298e-01]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [123]:
import time

small_array = np.array([1, 2, 3, 4, 5])

start_time = time.time()
np_sum_result = np.sum(small_array)
np_sum_time = time.time() - start_time

start_time = time.time()
builtin_sum_result = sum(small_array)
builtin_sum_time = time.time() - start_time

print(f"np.sum result: {np_sum_result}, time taken: {np_sum_time}")
print(f"built-in sum result: {builtin_sum_result}, time taken: {builtin_sum_time}")


np.sum result: 15, time taken: 0.0
built-in sum result: 15, time taken: 0.0


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [97]:
A = np.random.random((5, 5))
B = np.random.random((5, 5))

np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [124]:
array = np.array([1, 2, 3, 4, 5])

array.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [125]:
cartesian_coords = np.random.rand(10, 2)

x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]

r = np.sqrt(x**2 + y**2)

theta = np.arctan2(y, x)

polar_coords = np.column_stack((r, theta))

print("Cartesian coordinates:\n", cartesian_coords)
print("Polar coordinates (r, theta):\n", polar_coords)

Cartesian coordinates:
 [[0.36314224 0.94124058]
 [0.41954604 0.05462871]
 [0.47978702 0.93521936]
 [0.7279891  0.95966242]
 [0.22550231 0.4033299 ]
 [0.56385474 0.67114586]
 [0.24151008 0.12165964]
 [0.66914564 0.10864066]
 [0.79382357 0.94637055]
 [0.86673782 0.10321271]]
Polar coordinates (r, theta):
 [[1.00886377 1.20258019]
 [0.42308767 0.12948061]
 [1.05110934 1.09678639]
 [1.20454144 0.92182105]
 [0.46208906 1.06099235]
 [0.87656656 0.87205595]
 [0.27042224 0.46663959]
 [0.67790758 0.16095284]
 [1.23522187 0.87283555]
 [0.87286156 0.11852367]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [127]:
x = np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.62229098 0.68373955 0.78882583 0.1553241  0.91669599 0.73778793
 0.67937814 0.76754499 0.66601541 0.08405281]
[0.62229098 0.68373955 0.78882583 0.1553241  0.         0.73778793
 0.67937814 0.76754499 0.66601541 0.08405281]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [128]:
# np.add.at(vector, indices, 1)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
# np.add.at(vector, indices, second_vector)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [129]:
ubyte_size = 8
rgb_size = 3
num_colors = 3*8

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [131]:
x = np.random.random((4,4,4,4))
x.sum((-2,-1))

array([[7.65693172, 8.39383293, 8.23454654, 6.49159499],
       [7.64322509, 9.38408409, 9.25067512, 7.75505874],
       [6.2220715 , 9.11307534, 8.79211097, 8.43212271],
       [8.51300718, 7.91808503, 7.39106532, 8.97929598]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [135]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = np.array([Z[i:i+4] for i in range(len(Z)-3)])
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [259]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

rank = np.linalg.matrix_rank(matrix)

print("Matrix:\n", matrix)
print("Rank of the matrix:", rank)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [258]:
array = np.array([8, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5])
most_frequent = np.bincount(array)
print(np.argmax(most_frequent))
print(most_frequent)
print(array)
# can use unique if not ints

4
[0 0 2 3 4 1 0 0 1]
[8 2 2 3 3 3 4 4 4 4 5]


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [260]:
matrix = np.random.randint(0, 10, (10, 10))

# Function to extract all contiguous 3x3 blocks from a 10x10 matrix
def extract_blocks(matrix, block_size=3):
    rows, cols = matrix.shape
    blocks = np.lib.stride_tricks.sliding_window_view(matrix, (block_size, block_size))
    return blocks.reshape(-1, block_size, block_size)

# Extract the 3x3 blocks
blocks = extract_blocks(matrix)

print("Original 10x10 matrix:\n", matrix)
print("Extracted 3x3 blocks:\n", blocks)

Original 10x10 matrix:
 [[9 6 9 1 9 5 9 2 0 1]
 [0 4 3 9 1 8 2 7 0 1]
 [1 8 7 4 5 1 2 5 8 2]
 [1 4 1 1 9 4 1 8 7 9]
 [4 5 6 8 8 0 8 0 2 2]
 [6 5 5 0 8 7 8 7 7 3]
 [4 4 1 0 5 9 8 8 0 0]
 [2 8 6 7 9 3 9 0 4 1]
 [9 8 0 1 3 8 4 6 6 9]
 [0 9 1 7 5 0 2 7 4 2]]
Extracted 3x3 blocks:
 [[[9 6 9]
  [0 4 3]
  [1 8 7]]

 [[6 9 1]
  [4 3 9]
  [8 7 4]]

 [[9 1 9]
  [3 9 1]
  [7 4 5]]

 [[1 9 5]
  [9 1 8]
  [4 5 1]]

 [[9 5 9]
  [1 8 2]
  [5 1 2]]

 [[5 9 2]
  [8 2 7]
  [1 2 5]]

 [[9 2 0]
  [2 7 0]
  [2 5 8]]

 [[2 0 1]
  [7 0 1]
  [5 8 2]]

 [[0 4 3]
  [1 8 7]
  [1 4 1]]

 [[4 3 9]
  [8 7 4]
  [4 1 1]]

 [[3 9 1]
  [7 4 5]
  [1 1 9]]

 [[9 1 8]
  [4 5 1]
  [1 9 4]]

 [[1 8 2]
  [5 1 2]
  [9 4 1]]

 [[8 2 7]
  [1 2 5]
  [4 1 8]]

 [[2 7 0]
  [2 5 8]
  [1 8 7]]

 [[7 0 1]
  [5 8 2]
  [8 7 9]]

 [[1 8 7]
  [1 4 1]
  [4 5 6]]

 [[8 7 4]
  [4 1 1]
  [5 6 8]]

 [[7 4 5]
  [1 1 9]
  [6 8 8]]

 [[4 5 1]
  [1 9 4]
  [8 8 0]]

 [[5 1 2]
  [9 4 1]
  [8 0 8]]

 [[1 2 5]
  [4 1 8]
  [0 8 0]]

 [[2 5 8]
  [1 8 7

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [263]:
import numpy as np

class SymmetricArray(np.ndarray):
    def __new__(cls, shape, dtype=float, *args, **kwargs):
        # Create a zero-filled array and view it as an instance of the subclass
        obj = np.zeros(shape, dtype=dtype).view(cls)
        return obj

    def __setitem__(self, index, value):
        i, j = index
        super(SymmetricArray, self).__setitem__((i, j), value)
        super(SymmetricArray, self).__setitem__((j, i), value)

# Create a symmetric 2D array
shape = (5, 5)
Z = SymmetricArray(shape, dtype=float)

# Set values in the array
Z[1, 2] = 10
Z[3, 4] = 20

print("Symmetric Array:\n", Z)


Symmetric Array:
 [[ 0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0. 10.  0.  0.  0.]
 [ 0.  0.  0.  0. 20.]
 [ 0.  0.  0. 20.  0.]]


#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
# stack the vectors, matmul and sum on the first axis.

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [163]:
x = np.tile(np.arange(0,16),(16,1))
print(x)
x = x.reshape((4,4,4,4))
print(x.sum((0,3)))

x = np.tile(np.arange(0,16),(16,1))
print([[sum(x[i:i+4, j:j+4]) for i in range(0,15,4)] for j in range(0,15,4)])


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
[[ 24  88 152 216]
 [ 24  88 152 216]
 [ 24  88 152 216]
 [ 24  88 152 216]]
[[24, 24, 24, 24], [88, 88, 88, 88], [152, 152, 152, 152], [216, 216, 216, 216]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [164]:
turns = 100
board = np.zeros((16,16))

for turn in range(turns):
    num_neighbors = board[0:-2, 0:-2] + board[0:-2, 1:-1] + board[0:-2, 2:] + board[1:-1, 0:-2] + board[1:-1, 2:] + board[2:, 0:-2] + board[2:, 1:-1] + board[2:, 2:]

In [174]:
from IPython.display import clear_output

In [191]:
board = np.zeros((12,12))
board[5:8,5] = 1
board[5,6] = 1
board[6,7] = 1
print(board)
for i in range(100):
    time.sleep(2)
    clear_output(wait=True)
    counts = np.zeros(board.shape)
    counts[1:-1,1:-1] += (board[0:-2,0:-2] + board[0:-2,1:-1] + board[0:-2,2:] + board[1:-1,0:-2] + board[1:-1,2:] + board[2:,0:-2] + board[2:,1:-1] + board[2:,2:])
    board = np.where((board == 1) & ((counts < 2) | (counts > 3)), 0, board)
    board = np.where((board == 0) & (counts == 3), 1, board)
    print(board)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


KeyboardInterrupt: 

#### 89. How to get the n largest values of an array (★★★)

In [194]:
np.info(np.argpartition)

Perform an indirect partition along the given axis using the
algorithm specified by the `kind` keyword. It returns an array of
indices of the same shape as `a` that index data along the given
axis in partitioned order.

.. versionadded:: 1.8.0

Parameters
----------
a : array_like
    Array to sort.
kth : int or sequence of ints
    Element index to partition by. The k-th element will be in its
    final sorted position and all smaller elements will be moved
    before it and all larger elements behind it. The order of all
    elements in the partitions is undefined. If provided with a
    sequence of k-th it will partition all of them into their sorted
    position at once.

    .. deprecated:: 1.22.0
        Passing booleans as index is deprecated.
axis : int or None, optional
    Axis along which to sort. The default is -1 (the last axis). If
    None, the flattened array is used.
kind : {'introselect'}, optional
    Selection algorithm. Default is 'introselect'
order : str or list 

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
def cartesian_product(*arrays):
    la = len(arrays)
    dtype = np.result_type(*arrays)
    arr = np.empty([len(a) for a in arrays] + [la], dtype=dtype)
    for i, a in enumerate(np.ix_(*arrays)):
        arr[...,i] = a
    return arr.reshape(-1, la)

#### 91. How to create a record array from a regular array? (★★★)

In [195]:
regular_array = np.array([
    [1, 2.0, 'A'],
    [2, 3.5, 'B'],
    [3, 4.8, 'C']
])

dtype = [('field1', 'i4'), ('field2', 'f4'), ('field3', 'U1')]

record_array = np.array([
    (1, 2.0, 'A'),
    (2, 3.5, 'B'),
    (3, 4.8, 'C')
], dtype=dtype)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [199]:
z = np.arange(10)

z**3
np.power(z, 3)
np.einsum('i,i,i->i', z, z, z)
np.multiply(np.multiply(z, z), z)

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [216]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

print(np.isin(A[:,], B[0,:]))
print(np.isin(A[:,], B[1,:]))
print(np.isin(A[:,], B[0,:]).any(1)&np.isin(A[:,], B[1,:]).any(1))
print(A)
print(B)

[[ True False  True]
 [ True  True False]
 [False False False]
 [False False False]
 [ True False False]
 [False  True  True]
 [ True False False]
 [False False  True]]
[[ True False  True]
 [False  True False]
 [False  True  True]
 [False False False]
 [ True False  True]
 [ True  True False]
 [False False  True]
 [False False False]]
[ True  True False False  True  True  True False]
[[0 3 0]
 [2 0 3]
 [4 1 1]
 [3 3 3]
 [0 3 1]
 [1 0 2]
 [2 3 1]
 [3 4 2]]
[[0 2]
 [1 0]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [245]:
x = np.random.randint(0,5, (10,3))
print(x)
print(x[:,0])
print(x[:,0]==x.mean(1))
y_indices = x[:,0]==x.mean(1)

x[y_indices]

[[4 0 2]
 [4 3 4]
 [4 4 0]
 [2 4 0]
 [0 4 3]
 [2 4 0]
 [0 1 2]
 [3 2 3]
 [0 3 3]
 [4 2 4]]
[4 4 4 2 0 2 0 3 0 4]
[False False False  True False  True False False False False]


array([[2, 4, 0],
       [2, 4, 0]])

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [246]:
vector = np.arange(10)
max_bits = np.ceil(np.log2(vector.max() + 1)).astype(int)
binary_matrix = ((vector[:, None] & (1 << np.arange(max_bits))) > 0).astype(int)
print(vector)
print(binary_matrix)


[0 1 2 3 4 5 6 7 8 9]
[[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 1 0 0]
 [0 0 1 0]
 [1 0 1 0]
 [0 1 1 0]
 [1 1 1 0]
 [0 0 0 1]
 [1 0 0 1]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [248]:
x = np.random.randint(0, 2, (8, 3))
print(x)
y = np.unique(x, axis=0)
print(y)

[[1 1 1]
 [0 0 0]
 [0 1 0]
 [0 1 0]
 [0 1 1]
 [0 0 1]
 [0 1 0]
 [0 0 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [249]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])


inner_product = np.einsum('i,i', A, B)
print("Inner Product:", inner_product)
outer_product = np.einsum('i,j', A, B)
print("Outer Product:\n", outer_product)
elementwise_multiplication = np.einsum('i,i->i', A, B)
print("Element-wise Multiplication:", elementwise_multiplication)
sum_of_elements = np.einsum('i->', A)
print("Sum of Elements in A:", sum_of_elements)         

Inner Product: 32
Outer Product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Element-wise Multiplication: [ 4 10 18]
Sum of Elements in A: 6


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [250]:
???

Object `?` not found.


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [252]:
X = np.random.randint(0, 5, (10, 3))
n = 6
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X)
print(X[M])


[[0 3 0]
 [2 0 4]
 [3 3 2]
 [3 2 0]
 [0 1 2]
 [3 1 3]
 [3 0 0]
 [2 1 3]
 [3 1 3]
 [0 1 4]]
[[2 0 4]
 [2 1 3]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [253]:
X = np.random.randn(100)  

N = 1000

def bootstrap_confidence_interval(data, num_samples, ci=95):
    means = np.empty(num_samples)
    n = len(data)
    
    for i in range(num_samples):
        sample = np.random.choice(data, size=n, replace=True)
        means[i] = np.mean(sample)
    
    lower_percentile = (100 - ci) / 2
    upper_percentile = 100 - lower_percentile
    confidence_interval = np.percentile(means, [lower_percentile, upper_percentile])
    
    return confidence_interval

ci_95 = bootstrap_confidence_interval(X, N)
print("95% confidence interval for the mean:", ci_95)

95% confidence interval for the mean: [-0.17734934  0.20430261]
